#!/bin/sh

brew install git
brew install ruby-build
brew install rbenv
brew install nvm
brew install phantomjs
brew install vim
brew install postgres
brew install hub
brew install ngrok
brew install chromedriver
brew install stunnel

brew tap caskroom/cask
brew install brew-cask

brew cask install google-chrome
brew cask install atom
brew cask install visual-studio-code
brew cask install iterm2
brew cask install skype
brew cask install docker
brew cask install firefox
brew cask install kodi
brew cask install slack
